### ISSUE TITLE
The "n" binary is missing

### ISSUE THREAD

**Issue by syphernl** [Enrise/node-formula#7]
Seems like the `n` binary is missing which causes issues when people want to downgrade to specific versions:

```
----------
          ID: change_nodejs_version
    Function: cmd.run
        Name: sudo n 0.10.29
      Result: False
     Comment: Command "sudo n 0.10.29" run
     Started: 07:24:14.102430
    Duration: 21.804 ms
     Changes:   
              ----------
              pid:
                  15399
              retcode:
                  1
              stderr:
                  sudo: n: command not found
              stdout:
```
